---
deployment:
  tasks:
    - export DEPLOYPATH=/home/progresa/app.progresa-group.cl
    - /bin/bash -c "source ~/nodevenv/app.progresa-group.cl/20/bin/activate && cd $DEPLOYPATH && npm install --production=false && npx prisma generate && npm run build && mkdir -p tmp && touch tmp/restart.txt"
